version: '2'
services:
  influxdb:
    image: influxdb:1.2.2-alpine
    volumes:
      - ./docker/influxdb:/var/lib/influxdb
#    restart: always
  init:
    image: fraunhoferfit/dockerize
    command: bash -c "dockerize -wait tcp://influxdb:8086 -timeout 30s && 
                         curl -sS -POST 'http://influxdb:8086/query' --data-urlencode 'q=CREATE DATABASE hds'"
  hds:
    image: docker.linksmart.eu/hds/historical-datastore
#    build:
#      context: .
    ports:
      - "4000:4000"
      - "8085:8085"
    depends_on:
      - influxdb
      - init
    volumes:
      - ./docker/data:/data
#      - ./sample_conf:/conf
#    command: ["-conf", "/conf/myconf.json"]
#    restart: always
