version: '2'
services:
  influxdb:
    image: influxdb:1.2.2-alpine
    volumes:
      - ./docker/influxdb:/var/lib/influxdb
  init:
    build: 
      context: .
      dockerfile: Dockerize
    command: bash -c "dockerize -wait tcp://influxdb:8086 -timeout 30s && 
                         curl -sS -POST 'http://influxdb:8086/query' --data-urlencode 'q=CREATE DATABASE hds'"
  hds:
    build: .
    ports:
      - "4000:4000"
      - "8085:8085"
    depends_on:
      - influxdb
      - init
    volumes:
      - ./docker/data:/data
      - ./sample_conf:/conf
      