version: '2.4'

services:
  hds:
    build:
      context: .

  tester:
    build:
      context: .
      target: builder
    depends_on:
      - hds
    command: go test -mod=vendor ./...

# RUN
# docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit